import { DatabaseSync } from 'node:sqlite';
import { AsyncLocalStorage } from 'node:async_hooks';
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import ts from 'typescript';

// Test the real route handlers and real generated SQLite migrations.
// Only Cloudflare bindings and the platform identity provider are substituted.
const dir=resolve('.sites-runtime/workflow-test');mkdirSync(dir,{recursive:true});
function compile(from,to,replacements={}){let source=readFileSync(from,'utf8');for(const [a,b] of Object.entries(replacements))source=source.replaceAll(a,b);writeFileSync(resolve(dir,to),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
compile('lib/domain.ts','domain.mjs');compile('lib/access.ts','access.mjs');compile('lib/contract.ts','contract.mjs');
compile('lib/server.ts','server.mjs',{'cloudflare:workers':'./environment.mjs','@/app/chatgpt-auth':'./authentication.mjs',"'./domain'":"'./domain.mjs'","'./access'":"'./access.mjs'"});
const replace={'@/lib/server':'./server.mjs','@/lib/domain':'./domain.mjs','@/lib/contract':'./contract.mjs','@/lib/delivery':'./delivery.mjs','@/lib/recovery':'./recovery.mjs','cloudflare:workers':'./environment.mjs'};
compile('app/api/projects/route.ts','projects.mjs',replace);compile('app/api/projects/[id]/route.ts','detail.mjs',replace);compile('app/api/projects/[id]/export/route.ts','export.mjs',replace);compile('app/api/activity/route.ts','activity.mjs',replace);
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys = ON');
for(const name of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+name,'utf8'));
const auth=new AsyncLocalStorage();const blobs=new Map();
class Statement{constructor(query,values=[]){this.query=query;this.values=values;}bind(...values){return new Statement(this.query,values);}async first(){return sql.prepare(this.query).get(...this.values)||null;}async all(){return {results:sql.prepare(this.query).all(...this.values)};}run(){const r=sql.prepare(this.query).run(...this.values);return {success:true,meta:{changes:Number(r.changes)}};}}
const DB={prepare:q=>new Statement(q),batch:async statements=>{sql.exec('BEGIN');try{const r=statements.map(s=>s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const BUCKET={put:async(key,value)=>{blobs.set(key,value);},get:async key=>blobs.has(key)?{body:blobs.get(key),text:async()=>blobs.get(key)}:null,delete:async key=>{blobs.delete(key);},list:async({prefix=''})=>({objects:[...blobs.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key,uploaded:new Date()})),truncated:false})};
globalThis.__relayTest={env:{DB,BUCKET,RELAY_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),RELAY_DESTINATION_ORIGINS:'https://receiver.example.test'},auth};
const reportLog=console.log;const traceLogs=[];console.log=(...args)=>{if(typeof args[0]==='string'&&args[0].startsWith('{\"event\"'))traceLogs.push(args[0]);else reportLog(...args);};
writeFileSync(resolve(dir,'environment.mjs'),'export const env=globalThis.__relayTest.env;');writeFileSync(resolve(dir,'authentication.mjs'),'export async function getChatGPTUser(){return globalThis.__relayTest.auth.getStore()||null;}');
const domain=await import(pathToFileURL(resolve(dir,'domain.mjs')));const projects=await import(pathToFileURL(resolve(dir,'projects.mjs')));const detail=await import(pathToFileURL(resolve(dir,'detail.mjs')));const exporter=await import(pathToFileURL(resolve(dir,'export.mjs')));
const checks=[];function check(name,fn){fn();checks.push(name);}
const dataset=domain.parseCSV(domain.sampleCSV);const mapped=domain.suggestMapping(dataset.headers);
check('CSV parser handles BOM, escaped quotes, commas, and embedded newlines',()=>{const d=domain.parseCSV('\uFEFFa,b\r\n"A, B","line1\nline2"\r\n"C""D",z');assert.deepEqual(d.rows,[['A, B','line1\nline2'],['C"D','z']]);});
check('Malformed CSV is rejected',()=>{for(const v of ['a,a\nx,y','a,b\nx','a,b\n"x,y','a,b\nx"z,y'])assert.throws(()=>domain.parseCSV(v));});
check('Upload row limit is enforced',()=>assert.throws(()=>domain.parseCSV('a,b\n'+Array(501).fill('x,y').join('\n'))));
check('Demo contains exactly three blocking rows',()=>{const r=domain.validate({...dataset,mapping:mapped,exclusions:{}});assert.equal(r.accepted,9);assert.equal(r.invalid,3);assert.equal(r.issues.length,3);});
check('Duplicate IDs block every duplicate record',()=>{const d=domain.parseCSV(domain.sampleCSV);d.rows[1][0]=d.rows[0][0];const r=domain.validate({...d,mapping:mapped,exclusions:{}});assert.equal(r.issues.filter(i=>i.code==='duplicate').length,2);});
check('Impossible dates and nonfinite revenue are blocked',()=>{const d=domain.parseCSV(domain.sampleCSV);d.rows[0][5]='2026-02-30';d.rows[1][4]='Infinity';const r=domain.validate({...d,mapping:mapped,exclusions:{}});assert(r.issues.some(i=>i.field==='start_date'));assert(r.issues.some(i=>i.row===1&&i.field==='arr'));});
check('Missing and duplicated column mappings fail closed',()=>{assert.throws(()=>domain.checkMapping(dataset.headers,{...mapped,email:''}));assert.throws(()=>domain.checkMapping(dataset.headers,{...mapped,email:mapped.plan}));});
check('CSV export neutralizes spreadsheet formulas',()=>{const row=Object.fromEntries(domain.fields.map(f=>[f,'=1+1']));assert(domain.toCSV([row]).includes('"\'=1+1"'));});
const user={userId:'owner-a',email:'a@example.test',fullName:'Owner A'};
async function call(handler,{data,id,owner=user,origin='https://relay.test',workspace='',query='',method=data?'POST':'GET'}={}){const req=new Request('https://relay.test/api/projects'+(id?'/'+id:'')+query,{method,headers:{'content-type':'application/json',origin,...(workspace?{'x-workspace-id':workspace}:{})},...(data?{body:JSON.stringify(data)}:{})});return auth.run(owner,()=>handler(req,{params:Promise.resolve({id})}));}
async function expect(response,status){assert.equal(response.status,status,await response.clone().text());return response.json();}
await expect(await call(projects.GET,{owner:null}),401);checks.push('Unauthenticated API requests are rejected');
await expect(await call(projects.POST,{data:{},origin:'https://attacker.test'}),403);checks.push('Cross origin writes are rejected');
const requestId=crypto.randomUUID();const createBody={requestId,name:'Migration test',customer:'Test customer',sample:true};
const created=await expect(await call(projects.POST,{data:createBody}),201);const id=created.id;assert.equal(blobs.size,1);checks.push('CSV import persists a project, audit event, and original source');
await expect(await call(projects.POST,{data:createBody}),200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM projects').get().n,1);assert.equal(blobs.size,1);checks.push('Import retry is idempotent');
let d=await expect(await call(detail.GET,{id}),200);assert.equal(d.project.report.invalid,3);
const other={userId:'owner-b',email:'b@example.test'};
await expect(await call(detail.GET,{id,owner:other}),404);const empty=await expect(await call(projects.GET,{owner:other}),200);assert.equal(empty.projects.length,0);await expect(await call(detail.POST,{id,owner:other,data:{action:'validate',version:1}}),404);checks.push('Other accounts cannot list, read, or mutate the deployment');
await expect(await call(detail.POST,{id,data:{action:'release',version:d.project.version,note:'All checks reviewed'}}),422);assert.equal(sql.prepare('SELECT COUNT(*) n FROM releases').get().n,0);checks.push('Invalid data cannot be released');
await expect(await call(detail.POST,{id,data:{action:'exclude',version:d.project.version,row:2,reason:'no'}}),422);checks.push('Exclusions require a meaningful reason');
async function mutate(action,extra={}){d=await expect(await call(detail.POST,{id,data:{action,version:d.project.version,...extra}}),200);return d;}
await mutate('edit',{row:2,values:{email:'hello@atlas.example'}});assert.equal(d.project.report,null);
await expect(await call(detail.POST,{id,data:{action:'release',version:d.project.version,note:'Release without validation'}}),422);checks.push('Corrections invalidate validation and prevent premature release');
const beforeAudit=sql.prepare('SELECT COUNT(*) n FROM audit').get().n;
await expect(await call(detail.POST,{id,data:{action:'validate',version:1}}),409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit').get().n,beforeAudit);checks.push('Stale revision writes fail without an audit side effect');
await mutate('edit',{row:3,values:{arr:'1200'}});await mutate('edit',{row:5,values:{plan:'growth'}});await mutate('validate');assert.equal(d.project.report.accepted,12);assert.equal(d.project.report.invalid,0);
await mutate('release',{note:'Customer data contract verified'});const first=d.project.activeReleaseId;assert.equal(d.releases.length,1);checks.push('Corrected data validates and publishes an immutable release');
let res=await call(exporter.GET,{id,query:'?format=json'});assert.equal(res.status,200);const manifest=await res.json();assert.equal(manifest.records.length,12);const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(manifest.records))))).map(b=>b.toString(16).padStart(2,'0')).join('');assert.equal(digest,manifest.release.checksum);checks.push('Exported manifest checksum matches its actual records');
res=await call(exporter.GET,{id,query:'?format=csv'});assert.equal(res.status,200);assert.equal(domain.parseCSV(await res.text()).rows.length,12);checks.push('CSV release export can be imported back without record loss');
await expect(await call(exporter.GET,{id,owner:other,query:'?format=json'}),404);checks.push('Cross account exports are denied');
await expect(await call(detail.POST,{id,data:{action:'release',version:d.project.version,note:'Duplicate release attempt'}}),409);checks.push('An unchanged active release cannot be published twice');
await mutate('edit',{row:0,values:{arr:'97000'}});await mutate('validate');const summaries=await expect(await call(projects.GET),200);assert.equal(summaries.projects[0].status,'ready');checks.push('Validated working changes are distinguished from the active release');
await mutate('release',{note:'Updated contract value verified'});const second=d.project.activeReleaseId;assert.notEqual(first,second);await mutate('rollback',{releaseId:second,note:'Customer requested prior contract'});assert.equal(d.project.activeReleaseId,first);assert.equal(d.releases.length,2);checks.push('Rollback restores the previous registry pointer and retains both snapshots');
const original=await call(exporter.GET,{id,query:'?format=source'});assert.equal(await original.text(),domain.sampleCSV);checks.push('Corrections and rollback preserve the original uploaded bytes');
await mutate('exclude',{row:0,reason:'Outside this onboarding scope'});await mutate('validate');assert.equal(d.project.report.excluded,1);assert.equal(d.project.report.accepted,11);await mutate('restore',{row:0});assert.equal(Object.keys(d.project.exclusions).length,0);checks.push('Excluded rows are omitted from validation and can be restored');
// Two actions race at the same revision: only one mutation and audit event may commit.
const version=d.project.version;const audits=sql.prepare('SELECT COUNT(*) n FROM audit').get().n;
const race=await Promise.all([call(detail.POST,{id,data:{action:'validate',version}}),call(detail.POST,{id,data:{action:'validate',version}})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit').get().n,audits+1);checks.push('Concurrent updates commit exactly one state change and one audit event');
compile('lib/delivery.ts','delivery.mjs',{'cloudflare:workers':'./environment.mjs',"'./server'":"'./server.mjs'"});compile('lib/recovery.ts','recovery.mjs',{"'./server'":"'./server.mjs'","'./contract'":"'./contract.mjs'","'./domain'":"'./domain.mjs'"});
for(const route of ['workspaces','delivery','operations','recovery'])compile('app/api/'+route+'/route.ts',route+'-route.mjs',replace);
const workspaces=await import(pathToFileURL(resolve(dir,'workspaces-route.mjs')));const delivery=await import(pathToFileURL(resolve(dir,'delivery-route.mjs')));const operations=await import(pathToFileURL(resolve(dir,'operations-route.mjs')));const recovery=await import(pathToFileURL(resolve(dir,'recovery-route.mjs')));
let cfg={action:'settings',name:'Customer delivery team',requireApproval:true,retentionDays:30};await expect(await call(workspaces.POST,{data:cfg}),200);
d=await expect(await call(detail.GET,{id}),200);
await expect(await call(detail.POST,{id,data:{action:'release',version:d.project.version,note:'Attempt without a reviewer'}}),403);await expect(await call(detail.POST,{id,data:{action:'approve',version:d.project.version,note:'Attempt to approve my own edits'}}),403);checks.push('Workspace policy requires independent approval and blocks self approval');
const invitation=await expect(await call(workspaces.POST,{data:{action:'invite',email:other.email,role:'reviewer'}}),201);const third={userId:'owner-c',email:'c@example.test'};
await expect(await call(workspaces.POST,{owner:third,data:{action:'accept',code:invitation.code}}),403);
await expect(await call(workspaces.POST,{owner:other,data:{action:'accept',code:invitation.code}}),200);
const reviewerList=await expect(await call(projects.GET,{owner:other,workspace:user.userId}),200);assert.equal(reviewerList.projects.length,1);
await expect(await call(detail.POST,{owner:other,workspace:user.userId,id,data:{action:'edit',row:0,values:{arr:'1'},version:d.project.version}}),403);
d=await expect(await call(detail.POST,{owner:other,workspace:user.userId,id,data:{action:'approve',note:'Independently verified against the contract',version:d.project.version}}),200);assert.equal(d.project.approval.by,other.userId);
await mutate('release',{note:'Independent reviewer approved the dataset'});assert.equal(d.releases.find(r=>r.id===d.project.activeReleaseId).approvedBy,other.userId);checks.push('Email bound invitation grants review access without edit access and permits independent approval');
const viewerInvite=await expect(await call(workspaces.POST,{data:{action:'invite',email:third.email,role:'viewer'}}),201);await expect(await call(workspaces.POST,{owner:third,data:{action:'accept',code:viewerInvite.code}}),200);
await expect(await call(detail.GET,{owner:third,workspace:user.userId,id}),200);await expect(await call(workspaces.POST,{owner:third,workspace:user.userId,data:cfg}),403);await expect(await call(detail.POST,{owner:third,workspace:user.userId,id,data:{action:'approve',note:'Viewer should not approve this',version:d.project.version}}),403);checks.push('Viewer access cannot mutate workspace settings or approve a release');
await expect(await call(workspaces.POST,{data:{action:'remove',userId:other.userId}}),200);await expect(await call(projects.GET,{owner:other,workspace:user.userId}),403);checks.push('Revoked membership immediately blocks workspace access');
const event=sql.prepare("SELECT evidence_json,request_id FROM audit WHERE action = 'Row corrected' LIMIT 1").get();const evidence=JSON.parse(event.evidence_json);assert.equal(evidence.changes[0].field,'email');assert.equal(evidence.changes[0].before,'hello@atlas');assert.equal(evidence.changes[0].after,'hello@atlas.example');assert(event.request_id);const releaseEvidence=d.releases.find(r=>r.id===d.project.activeReleaseId);assert.equal(releaseEvidence.contract.id,'relay.accounts');assert.equal(releaseEvidence.contractHash.length,64);assert.equal(releaseEvidence.sourceChecksum.length,64);checks.push('Audit evidence records exact field changes, request IDs, contract snapshots, and source checksums');
await expect(await call(delivery.POST,{data:{action:'configure',baseUrl:'http://127.0.0.1',token:'test-only-token'}}),422);
await expect(await call(delivery.POST,{data:{action:'configure',baseUrl:'https://unapproved.example.test',token:'test-only-token'}}),422);
await expect(await call(delivery.POST,{data:{action:'configure',baseUrl:'https://receiver.example.test',token:'test-only-token'}}),200);
const secret=sql.prepare('SELECT encrypted_token FROM destinations').get().encrypted_token;assert(!secret.includes('test-only-token'));const configResponse=await expect(await call(delivery.GET),200);assert(!JSON.stringify(configResponse).includes('encrypted_token'));checks.push('Destination origins are allowlisted and credentials are encrypted and omitted from reads');
const nativeFetch=globalThis.fetch;let receiverMode='ok';const received=new Map();let sendCount=0;
globalThis.fetch=async(url,options)=>{assert(url.startsWith('https://receiver.example.test/releases'));assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,'Bearer test-only-token');if(options.method==='POST'){sendCount++;const data=JSON.parse(options.body);assert.equal(options.headers['Idempotency-Key'],data.releaseId);received.set(data.releaseId,{releaseId:data.releaseId,checksum:data.checksum,recordCount:data.recordCount,status:'committed',receiptId:'receipt-'+data.releaseId});if(receiverMode==='timeout')throw new Error('Simulated response loss');return Response.json(received.get(data.releaseId));}const rid=decodeURIComponent(url.split('/').at(-1));if(!received.has(rid))return new Response('',{status:404});return Response.json({...received.get(rid),...(receiverMode==='bad-receipt'?{checksum:'wrong'}:{})});};
let queued=await expect(await call(delivery.POST,{data:{action:'queue',projectId:id,releaseId:d.project.activeReleaseId}}),200);let sent=await expect(await call(delivery.POST,{data:{action:'send',id:queued.id}}),200);assert.equal(sent.status,'acknowledged');const sends=sendCount;await expect(await call(delivery.POST,{data:{action:'send',id:queued.id}}),200);assert.equal(sendCount,sends);checks.push('Delivery requires a matching committed receipt and avoids sending an acknowledged job twice');
await expect(await call(workspaces.POST,{data:{...cfg,requireApproval:false}}),200);await mutate('edit',{row:0,values:{arr:'98000'}});await mutate('validate');await mutate('release',{note:'Receipt recovery scenario'});queued=await expect(await call(delivery.POST,{data:{action:'queue',projectId:id,releaseId:d.project.activeReleaseId}}),200);
receiverMode='timeout';sent=await expect(await call(delivery.POST,{data:{action:'send',id:queued.id}}),200);assert.equal(sent.status,'uncertain');await expect(await call(delivery.POST,{data:{action:'send',id:queued.id}}),409);
receiverMode='bad-receipt';let reconciled=await expect(await call(delivery.POST,{data:{action:'reconcile',id:queued.id}}),200);assert.equal(reconciled.status,'uncertain');receiverMode='ok';reconciled=await expect(await call(delivery.POST,{data:{action:'reconcile',id:queued.id}}),200);assert.equal(reconciled.status,'acknowledged');checks.push('Response loss and mismatched receipts remain uncertain until successful reconciliation');globalThis.fetch=nativeFetch;
const ops=await expect(await call(operations.GET),200);assert(ops.stats.total>0);assert(ops.stats.rejected>0);assert.equal(ops.health.objectStorage,'reachable');assert(ops.requests.every(r=>r.id&&r.duration_ms>=0));assert(!traceLogs.join('\n').includes('test-only-token'));checks.push('Operations expose request references and rejection metrics without logging credentials');
const backed=await expect(await call(recovery.POST,{data:{action:'backup',projectId:id}}),201);assert(backed.objectCount>=4);
await expect(await call(recovery.GET,{owner:third,workspace:user.userId}),403);
const beforeRestore=await expect(await call(detail.GET,{id}),200);const restored=await expect(await call(recovery.POST,{data:{action:'restoreBackup',id:backed.id}}),201);const recovered=await expect(await call(detail.GET,{id:restored.projectId}),200);assert.notEqual(recovered.project.id,id);assert.deepEqual(recovered.project.rows,beforeRestore.project.rows);assert.equal(recovered.releases.length,beforeRestore.releases.length);assert(recovered.audit.some(a=>a.action==='Backup restored'));assert.equal(blobs.get(recovered.project.sourceKey),domain.sampleCSV);checks.push('Restore drill recovers source bytes, working records, snapshots, and audit history into a new deployment');
const manifestKey=sql.prepare('SELECT manifest_key FROM backups WHERE id = ?').get(backed.id).manifest_key;const backupManifest=JSON.parse(blobs.get(manifestKey));const objectKey=backupManifest.files[0].key;const validObject=blobs.get(objectKey);blobs.set(objectKey,validObject+' ');const projectCount=sql.prepare('SELECT COUNT(*) n FROM projects').get().n;await expect(await call(recovery.POST,{data:{action:'restoreBackup',id:backed.id}}),422);assert.equal(sql.prepare('SELECT COUNT(*) n FROM projects').get().n,projectCount);blobs.set(objectKey,validObject);checks.push('A corrupt backup fails verification before recovered data is created');
const bundleResponse=await call(recovery.GET,{query:'?export='+backed.id});assert.equal(bundleResponse.status,200);const bundle=await bundleResponse.text();const lines=bundle.trim().split('\n').map(JSON.parse);assert.equal(lines.at(-1).type,'complete');assert.equal(lines.at(-1).objects,backupManifest.files.length);writeFileSync(resolve(dir,'recovery.ndjson'),bundle);checks.push('Recovery bundle streams all verified objects with a completion marker');
await expect(await call(recovery.POST,{data:{action:'trash',projectId:restored.projectId,name:recovered.project.name}}),200);await expect(await call(detail.GET,{id:restored.projectId}),404);await expect(await call(recovery.POST,{data:{action:'restoreTrash',projectId:restored.projectId}}),200);await expect(await call(detail.GET,{id:restored.projectId}),200);checks.push('Trash is reversible and hides deployments from normal access');
await expect(await call(recovery.POST,{data:{action:'trash',projectId:restored.projectId,name:recovered.project.name}}),200);sql.prepare('UPDATE projects SET deleted_at = ? WHERE id = ?').run(new Date(Date.now()-31*86400000).toISOString(),restored.projectId);
const normalDelete=BUCKET.delete;let blockedRestore=false;BUCKET.delete=async key=>{if(key===recovered.project.sourceKey){const res=await call(recovery.POST,{data:{action:'restoreTrash',projectId:restored.projectId}});blockedRestore=res.status===409;}return normalDelete(key);};
const cleaned=await expect(await call(recovery.POST,{data:{action:'cleanup',confirmation:'DELETE EXPIRED DATA'}}),200);BUCKET.delete=normalDelete;assert.equal(cleaned.projects,1);assert(blockedRestore);assert(!blobs.has(recovered.project.sourceKey));assert(blobs.has(beforeRestore.project.sourceKey));checks.push('Retention purges only expired trash and prevents restoration during deletion');
const {verifyRecovery}=await import('../scripts/verify-recovery.mjs');const offline=await verifyRecovery(resolve(dir,'recovery.ndjson'),resolve(dir,'offline-'+crypto.randomUUID()));assert.equal(offline.verifiedObjects,backupManifest.files.length);assert.equal(readFileSync(resolve(offline.output,'source.csv'),'utf8'),domain.sampleCSV);checks.push('Independent recovery verifier validates the exported bundle without Cloudflare and recovers the original CSV');
await expect(await call(projects.POST,{data:{...createBody,name:'Changed retry content'}}),409);checks.push('Reusing an import request ID with different content is rejected');
console.log(checks.map((c,i)=>String(i+1).padStart(2,'0')+' PASS '+c).join('\n'));console.log('\n'+checks.length+' checks passed. Real SQLite migrations and application route handlers; platform authentication and object storage are simulated.');
