import { db, bucket, getProject, workspaceEvent, settings, HttpError, type Actor } from './server';
import { digest } from './contract';
import type { Project, Release } from './domain';
type Entry={key:string;kind:'project'|'source'|'release'|'audit';id?:string;hash:string;size:number};
type Manifest={format:'relay.backup.v1';projectId:string;workspaceId:string;version:number;createdAt:string;files:Entry[]};
async function put(key:string,text:string){await bucket().put(key,text,{httpMetadata:{contentType:'application/json'}});return {hash:await digest(text),size:new TextEncoder().encode(text).length};}
export async function backupProject(actor:Actor,projectId:string){
 const p=await getProject(projectId,actor.workspaceId);const id=crypto.randomUUID();const prefix='backups/'+actor.workspaceId+'/'+id+'/';const manifestKey=prefix+'manifest.json';const createdAt=new Date().toISOString();const expiry=new Date(Date.now()+(await settings(actor)).retention_days*86400000).toISOString();const files:Entry[]=[];
 await db().prepare('INSERT INTO backups (id,workspace_id,project_id,project_name,manifest_key,manifest_hash,status,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,actor.workspaceId,p.id,p.name,manifestKey,'','staging',createdAt,expiry).run();
 try{
  const source=await bucket().get(p.sourceKey);if(!source)throw new HttpError(503,'Original source is missing. Backup was not marked ready.');
  const sourceText=await source.text();files.push({key:prefix+'project.json',kind:'project',...await put(prefix+'project.json',JSON.stringify(p))});files.push({key:prefix+'source.csv',kind:'source',...await put(prefix+'source.csv',sourceText)});
  let after='';for(;;){const row=await db().prepare('SELECT id,metadata,records FROM releases WHERE owner_id = ? AND project_id = ? AND id > ? ORDER BY id LIMIT 1').bind(actor.workspaceId,p.id,after).first<{id:string;metadata:string;records:string}>();if(!row)break;after=row.id;const key=prefix+'releases/'+row.id+'.json';files.push({key,kind:'release',id:row.id,...await put(key,JSON.stringify(row))});if(files.length>2000)throw new HttpError(422,'Backup exceeds the supported object count.');}
  after='';for(;;){const page=await db().prepare('SELECT * FROM audit WHERE owner_id = ? AND project_id = ? AND id > ? ORDER BY id LIMIT 100').bind(actor.workspaceId,p.id,after).all<{id:string}>();if(!page.results.length)break;after=page.results[page.results.length-1].id;const key=prefix+'audit/'+after+'.json';files.push({key,kind:'audit',...await put(key,JSON.stringify(page.results))});if(files.length>2000)throw new HttpError(422,'Backup exceeds the supported object count.');}
  const manifest:Manifest={format:'relay.backup.v1',projectId:p.id,workspaceId:actor.workspaceId,version:p.version,createdAt,files};const saved=await put(manifestKey,JSON.stringify(manifest));
  const updated=await db().prepare("UPDATE backups SET manifest_hash = ?,status = 'ready' WHERE id = ? AND workspace_id = ? AND EXISTS (SELECT 1 FROM projects WHERE id = ? AND owner_id = ? AND version = ? AND deleted_at IS NULL)").bind(saved.hash,id,actor.workspaceId,p.id,actor.workspaceId,p.version).run();if(updated.meta.changes!==1)throw new HttpError(409,'The deployment changed while backup was running. Create another snapshot.');
  await workspaceEvent(actor,'Backup created',{backupId:id,projectId:p.id,version:p.version,manifestHash:saved.hash,objectCount:files.length,expiresAt:expiry}).run();return {id,manifestHash:saved.hash,objectCount:files.length};
 }catch(e){await Promise.allSettled([...files.map(f=>bucket().delete(f.key)),bucket().delete(manifestKey)]);await db().prepare("UPDATE backups SET status = 'failed' WHERE id = ? AND workspace_id = ?").bind(id,actor.workspaceId).run();throw e;}
}
export async function loadManifest(actor:Actor,id:string){
 const row=await db().prepare("SELECT * FROM backups WHERE id = ? AND workspace_id = ? AND status = 'ready'").bind(id,actor.workspaceId).first<{manifest_key:string;manifest_hash:string}>();if(!row)throw new HttpError(404,'Ready backup not found.');const object=await bucket().get(row.manifest_key);if(!object)throw new HttpError(503,'Backup manifest is unavailable.');const text=await object.text();if(await digest(text)!==row.manifest_hash)throw new HttpError(422,'Backup manifest checksum failed.');const manifest=JSON.parse(text) as Manifest;
 const prefix='backups/'+actor.workspaceId+'/'+id+'/';if(manifest.format!=='relay.backup.v1'||manifest.workspaceId!==actor.workspaceId||!Array.isArray(manifest.files)||manifest.files.length>2000||manifest.files.some(f=>!f.key.startsWith(prefix)))throw new HttpError(422,'Backup manifest is invalid.');return manifest;
}
export async function readEntry(entry:Entry){const object=await bucket().get(entry.key);if(!object)throw new HttpError(503,'A backup object is missing.');const text=await object.text();if(await digest(text)!==entry.hash||new TextEncoder().encode(text).length!==entry.size)throw new HttpError(422,'Backup object checksum failed. Restore was stopped.');return text;}
export async function restoreBackup(actor:Actor,id:string){
 const manifest=await loadManifest(actor,id);const pe=manifest.files.find(f=>f.kind==='project');const se=manifest.files.find(f=>f.kind==='source');if(!pe||!se)throw new HttpError(422,'Backup is incomplete.');
 // Verify every object before creating any recovered data.
 for(const entry of manifest.files)await readEntry(entry);
 const original=JSON.parse(await readEntry(pe)) as Project;const source=await readEntry(se);const newId=crypto.randomUUID();const sourceKey='sources/'+actor.workspaceId+'/'+newId+'/'+crypto.randomUUID()+'.csv';const restoredAt=new Date().toISOString();const mutation=crypto.randomUUID();const releaseIds=new Map(manifest.files.filter(f=>f.kind==='release').map(f=>[f.id!,crypto.randomUUID()]));
 const p:Project={...original,id:newId,name:(original.name+' · Restored').slice(0,80),sourceKey,sourceChecksum:await digest(source),createdAt:restoredAt,updatedAt:restoredAt,version:original.version+1,lastEditorId:actor.userId,approval:null,report:null,workingChanged:true,activeReleaseId:original.activeReleaseId?releaseIds.get(original.activeReleaseId)||null:null};
 await bucket().put(sourceKey,source,{httpMetadata:{contentType:'text/csv'}});
 try{
  const count=await db().prepare('SELECT COUNT(*) n FROM projects WHERE owner_id = ?').bind(actor.workspaceId).first<{n:number}>();if((count?.n||0)>=100)throw new HttpError(422,'Workspace limit reached. Clear expired trash before restoring.');
  await db().prepare('INSERT INTO projects (id,owner_id,document,version,mutation_id,updated_at,deleted_at,purge_token) VALUES (?,?,?,?,?,?,?,?)').bind(newId,actor.workspaceId,JSON.stringify(p),p.version,mutation,restoredAt,restoredAt,mutation).run();
  for(const f of manifest.files){
   if(f.kind==='release'){const row=JSON.parse(await readEntry(f));const metadata=JSON.parse(row.metadata) as Release;const releaseId=releaseIds.get(metadata.id)!;const previous=metadata.previousReleaseId?releaseIds.get(metadata.previousReleaseId)||null:null;await db().prepare('INSERT INTO releases (id,project_id,owner_id,metadata,records,created_at) VALUES (?,?,?,?,?,?)').bind(releaseId,newId,actor.workspaceId,JSON.stringify({...metadata,id:releaseId,projectId:newId,previousReleaseId:previous,recoveredFromReleaseId:metadata.id}),row.records,metadata.createdAt).run();}
   if(f.kind==='audit'){const rows=JSON.parse(await readEntry(f));for(const a of rows)await db().prepare('INSERT INTO audit (id,project_id,owner_id,actor,action,detail,created_at,evidence_json,project_version,request_id) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),newId,actor.workspaceId,a.actor,a.action,a.detail,a.created_at,JSON.stringify({recoveredFromProjectId:manifest.projectId,recoveredFromAuditId:a.id,evidence:JSON.parse(a.evidence_json||'{}')}),a.project_version||0,a.request_id||null).run();}
  }
  await db().batch([db().prepare('UPDATE projects SET deleted_at = NULL,purge_token = NULL WHERE id = ? AND owner_id = ? AND mutation_id = ?').bind(newId,actor.workspaceId,mutation),db().prepare('INSERT INTO audit (id,project_id,owner_id,actor,action,detail,created_at,evidence_json,project_version,request_id) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),newId,actor.workspaceId,actor.email,'Backup restored','Recovered into a new deployment. Original deployment unchanged.',restoredAt,JSON.stringify({backupId:id,sourceProjectId:manifest.projectId,sourceVersion:manifest.version}),p.version,actor.requestId),workspaceEvent(actor,'Backup restored',{backupId:id,newProjectId:newId})]);
  return {projectId:newId};
 }catch(e){try{await db().batch([db().prepare('DELETE FROM audit WHERE project_id = ? AND owner_id = ?').bind(newId,actor.workspaceId),db().prepare('DELETE FROM releases WHERE project_id = ? AND owner_id = ?').bind(newId,actor.workspaceId),db().prepare('DELETE FROM projects WHERE id = ? AND owner_id = ? AND deleted_at IS NOT NULL').bind(newId,actor.workspaceId)]);await bucket().delete(sourceKey);}catch{console.error(JSON.stringify({event:'restore_cleanup_required',requestId:actor.requestId}));}throw e;}
}
export async function exportBackup(actor:Actor,id:string){
 const manifest=await loadManifest(actor,id);
 const stream=new ReadableStream<Uint8Array>({async start(controller){const encode=(v:unknown)=>new TextEncoder().encode(JSON.stringify(v)+'\n');try{controller.enqueue(encode({type:'manifest',manifest}));for(const f of manifest.files)controller.enqueue(encode({type:'object',key:f.key,hash:f.hash,text:await readEntry(f)}));controller.enqueue(encode({type:'complete',objects:manifest.files.length}));controller.close();}catch(e){controller.error(e);}}});
 return new Response(stream,{headers:{'Content-Type':'application/x-ndjson','Content-Disposition':'attachment; filename="relay_recovery.ndjson"','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
}
export async function cleanup(actor:Actor){
 const config=await settings(actor);const cutoff=new Date(Date.now()-config.retention_days*86400000).toISOString();
 const expired=await db().prepare('SELECT id,document FROM projects WHERE owner_id = ? AND deleted_at IS NOT NULL AND deleted_at < ? AND (purge_lease_until IS NULL OR purge_lease_until < ?) LIMIT 20').bind(actor.workspaceId,cutoff,new Date().toISOString()).all<{id:string;document:string}>();let projects=0;
 for(const row of expired.results){const token=crypto.randomUUID();const claim=await db().prepare('UPDATE projects SET purge_token = ?,purge_lease_until = ? WHERE id = ? AND owner_id = ? AND deleted_at < ? AND (purge_lease_until IS NULL OR purge_lease_until < ?)').bind(token,new Date(Date.now()+60000).toISOString(),row.id,actor.workspaceId,cutoff,new Date().toISOString()).run();if(claim.meta.changes!==1)continue;const p=JSON.parse(row.document) as Project;await bucket().delete(p.sourceKey);await db().batch([db().prepare('DELETE FROM audit WHERE project_id = ? AND owner_id = ?').bind(row.id,actor.workspaceId),db().prepare('DELETE FROM releases WHERE project_id = ? AND owner_id = ?').bind(row.id,actor.workspaceId),db().prepare('DELETE FROM deliveries WHERE project_id = ? AND workspace_id = ?').bind(row.id,actor.workspaceId),db().prepare('DELETE FROM projects WHERE id = ? AND owner_id = ? AND purge_token = ?').bind(row.id,actor.workspaceId,token)]);projects++;}
 const old=await db().prepare('SELECT id,manifest_key FROM backups WHERE workspace_id = ? AND expires_at < ? LIMIT 20').bind(actor.workspaceId,new Date().toISOString()).all<{id:string;manifest_key:string}>();let backups=0;
 for(const b of old.results){const prefix='backups/'+actor.workspaceId+'/'+b.id+'/';await db().prepare("UPDATE backups SET status = 'deleting' WHERE id = ? AND workspace_id = ?").bind(b.id,actor.workspaceId).run();let cursor:string|undefined;do{const page=await bucket().list({prefix,cursor,limit:100});for(const o of page.objects)await bucket().delete(o.key);cursor=page.truncated?page.cursor:undefined;}while(cursor);await db().prepare('DELETE FROM backups WHERE id = ? AND workspace_id = ?').bind(b.id,actor.workspaceId).run();backups++;}
 await db().prepare('DELETE FROM requests WHERE workspace_id = ? AND created_at < ?').bind(actor.workspaceId,new Date(Date.now()-7*86400000).toISOString()).run();
 let orphanedSources=0;let cursor:string|undefined;let scanned=0;do{const page=await bucket().list({prefix:'sources/'+actor.workspaceId+'/',cursor,limit:100});for(const o of page.objects){scanned++;if(o.uploaded.getTime()>Date.now()-86400000)continue;const referenced=await db().prepare("SELECT id FROM projects WHERE owner_id = ? AND json_extract(document,'$.sourceKey') = ?").bind(actor.workspaceId,o.key).first();if(!referenced){await bucket().delete(o.key);orphanedSources++;}}cursor=page.truncated?page.cursor:undefined;}while(cursor&&scanned<1000);
 await workspaceEvent(actor,'Retention cleanup completed',{projects,backups,orphanedSources,scanned,scanLimited:!!cursor,retentionDays:config.retention_days}).run();return {projects,backups,orphanedSources,scanLimited:!!cursor};
}
